"""Collect synthesized output files generated by the --synthesize flag.

Each synthesized file is written to the matching subdirectory and a metadata
entry is appended to the corresponding JSONL log.  Duplicates are detected by
SHA-1 of the output bytes and silently skipped.

Directory layout (all data/ dirs are gitignored):
    Synthesized/Audio/data/   -- MP3 TTS outputs  + synth_audio.jsonl
    Synthesized/Image/data/   -- PNG image outputs + synth_image.jsonl
    Synthesized/Text/data/    -- TXT file outputs  + synth_text.jsonl
    Synthesized/Video/data/   -- MKV video outputs + synth_video.jsonl

Schema (all types share the same fields):
    content_hash  -- SHA-1[:16] of the synthesized bytes (deduplication key)
    filename      -- saved filename (<date>_<user>_<hash>.<ext>)
    synth_type    -- output type: 'audio' | 'image' | 'text' | 'video'
    source_type   -- input type that triggered the synthesis: 'audio' | 'image' | 'text' | 'video'
    translated_text -- the translated text that was synthesized
    target_language -- BCP-47 / ISO 639-1 code of the synthesis language
    username      -- Discord username of the requester
    timestamp     -- UTC ISO 8601
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

_SYNTH_ROOT = Path(__file__).parent

_DATA_DIR: dict[str, Path] = {
    "audio": _SYNTH_ROOT / "Audio" / "data",
    "image": _SYNTH_ROOT / "Image" / "data",
    "text":  _SYNTH_ROOT / "Text"  / "data",
    "video": _SYNTH_ROOT / "Video" / "data",
}

_JSONL_FILE: dict[str, str] = {
    "audio": "synth_audio.jsonl",
    "image": "synth_image.jsonl",
    "text":  "synth_text.jsonl",
    "video": "synth_video.jsonl",
}

_EXT: dict[str, str] = {
    "audio": ".mp3",
    "image": ".png",
    "text":  ".txt",
    "video": ".mkv",
}


def _content_hash(data: bytes) -> str:
    return hashlib.sha1(data).hexdigest()[:16]


def _existing_hashes(jsonl_path: Path) -> set[str]:
    if not jsonl_path.exists():
        return set()
    hashes: set[str] = set()
    with jsonl_path.open(encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            try:
                h = json.loads(line).get("content_hash")
                if h:
                    hashes.add(h)
            except (json.JSONDecodeError, Exception):
                pass
    return hashes


def save_synthesis(
    output_bytes: bytes,
    synth_type: str,
    *,
    translated_text: str,
    source_type: str,
    target_language: str,
    username: str | None = None,
) -> Path | None:
    """Save a synthesized output file and append metadata to the JSONL log.

    Args:
        output_bytes:    Raw bytes of the synthesized file (MP3 / PNG / TXT / MKV).
        synth_type:      Output type: 'audio', 'image', 'text', or 'video'.
        translated_text: The translated text that was synthesized.
        source_type:     Input type that triggered the synthesis.
        target_language: Language code used for synthesis.
        username:        Discord username of the requester.

    Returns:
        Path of the saved file, or None if skipped (unknown type, empty bytes,
        or duplicate content hash).
    """
    if synth_type not in _DATA_DIR:
        return None
    if not output_bytes:
        return None

    data_dir = _DATA_DIR[synth_type]
    data_dir.mkdir(parents=True, exist_ok=True)

    jsonl_path = data_dir / _JSONL_FILE[synth_type]
    content_hash = _content_hash(output_bytes)

    if content_hash in _existing_hashes(jsonl_path):
        return None

    date_str = datetime.now(timezone.utc).strftime("%Y%m%d")
    safe_user = (username or "unknown").replace("/", "_").replace("\\", "_")
    filename = f"{date_str}_{safe_user}_{content_hash}{_EXT[synth_type]}"
    out_path = data_dir / filename
    out_path.write_bytes(output_bytes)

    entry = {
        "content_hash":   content_hash,
        "filename":       filename,
        "synth_type":     synth_type,
        "source_type":    source_type,
        "translated_text": translated_text,
        "target_language": target_language,
        "username":       username,
        "timestamp":      datetime.now(timezone.utc).isoformat(),
    }
    with jsonl_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    return out_path


def load_submissions(synth_type: str) -> list[dict]:
    """Return all collected synthesis records for a given type."""
    jsonl_path = _DATA_DIR[synth_type] / _JSONL_FILE[synth_type]
    if not jsonl_path.exists():
        return []
    with jsonl_path.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def dataset_stats(synth_type: str | None = None) -> dict:
    """Return a summary of collected synthesis outputs.

    If synth_type is None, aggregates across all four types.
    """
    types = [synth_type] if synth_type else list(_DATA_DIR)
    total = 0
    by_type: dict[str, int] = {}
    by_lang: dict[str, int] = {}
    for t in types:
        records = load_submissions(t)
        by_type[t] = len(records)
        total += len(records)
        for r in records:
            lang = r.get("target_language", "unknown")
            by_lang[lang] = by_lang.get(lang, 0) + 1
    return {
        "total": total,
        "by_type": by_type,
        "by_language": by_lang,
    }


if __name__ == "__main__":
    stats = dataset_stats()
    print(f"Total synthesized outputs: {stats['total']}")
    print("By type:")
    for t, n in stats["by_type"].items():
        print(f"  {t}: {n}")
    print("By target language:")
    for lang, n in sorted(stats["by_language"].items(), key=lambda x: -x[1]):
        print(f"  {lang}: {n}")
